### ISSUE TITLE
Need Endpoint to get User's role.

### ISSUE THREAD

**Issue by rgwozdz** [okfn/ckanext-cadastaroles#20]
Need an endpoint to get current user's role.

**Comment by joetsoi** [comment]
try `organization_list_for_user` I'll have to check the change log to see when it was added, it should be in 2.4 

https://github.com/ckan/ckan/blob/master/ckan/logic/action/get.py#L677

it might have some weird behaviour, if so I can just add an action where you give a user id and group and it'll return the role

**Comment by rgwozdz** [comment]
I don't think this gets us what we need...I see an array of organizations, with details of each org.  But unfortunately, not property providing the user's role in each org.

**Comment by joetsoi** [comment]
ok I'll add one in

**Comment by joetsoi** [comment]
example

```
http://127.0.0.1:5000/api/action/user_role_show?user_id=bob&organization_id=org
{

    "help": "http://127.0.0.1:5000/api/3/action/help_show?name=user_role_show",
    "success": true,
    "result": null

}
```

```
http://127.0.0.1:5000/api/action/user_role_show?user_id=joe&organization_id=org
{

    "help": "http://127.0.0.1:5000/api/3/action/help_show?name=user_role_show",
    "success": true,
    "result": 

    {
        "user_id": "a146f20c-4b9c-424d-b552-bc04651204b8",
        "role": "admin",
        "organization_id": "d393c46e-187e-4934-a263-9d2d70336912",
        "state": "active",
        "revision_id": "44f3421a-63b1-46f4-b946-f8a469cdc226",
        "id": "224ea539-d8fa-4cce-823a-ee13e7b6911a"
    }

}
```

**Comment by joetsoi** [comment]
realised this need you to to be able to provide user_name or organization_name added this in 74c081e6d2f63f4afda518a99a3cec887dbe2c90
